# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Driver'),
        ),
    ]
