# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buissnesspartner',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='luggage_number',
            field=models.IntegerField(help_text=b'Nombre de bagage authoris\xc3\xa9', verbose_name=b'Nombre de baggage'),
        ),
    ]
