# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='clients',
            field=models.ManyToManyField(blank=True, to='Back_Source.Client'),
        ),
    ]
