# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('child_seat', models.BooleanField()),
                ('number_place', models.IntegerField()),
                ('luggage_number', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=9)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('insurance', models.FileField(upload_to=b'')),
                ('insurance_card', models.FileField(upload_to=b'')),
                ('registration_card', models.FileField(upload_to=b'')),
                ('front', models.ImageField(upload_to=b'')),
                ('back', models.ImageField(upload_to=b'')),
                ('revenues', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='travel',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Vehicle'),
        ),
    ]
