# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('destination_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('date', models.DateField(auto_now=True, verbose_name=b'Date R\xc3\xa9servation')),
                ('passengers', models.IntegerField(verbose_name=b'Nombre de passagers')),
                ('luggage_number', models.IntegerField(verbose_name=b'Nombre de baggages')),
                ('flight', models.CharField(max_length=200, verbose_name=b'Vol')),
                ('arrive_time', models.DateTimeField(blank=True, verbose_name=b"Date d'Arriv\xc3\xa9e")),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name=b'Distance D\xc3\xa9part-Destination')),
                ('status', models.CharField(default=b'En cours de validation', max_length=100)),
                ('payement_type', models.CharField(default=b'Aucun', max_length=5)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Airport', verbose_name=b'A\xc3\xa9roport')),
            ],
            options={
                'verbose_name': 'R\xe9servation Op\xe9rateur',
                'verbose_name_plural': 'R\xe9servations Op\xe9rateur',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('buissnesspartner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Back_Source.BuissnessPartner')),
            ],
            options={
                'verbose_name': 'Op\xe9rateur',
            },
            bases=('Back_Source.buissnesspartner',),
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Cat\xe9gorie de voiture', 'verbose_name_plural': 'Cat\xe9gories de voiture'},
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='year',
        ),
        migrations.AddField(
            model_name='booking',
            name='account',
            field=models.IntegerField(default=5, verbose_name=b'Accompte'),
        ),
        migrations.AddField(
            model_name='booking',
            name='accountType',
            field=models.CharField(default=b'CB', max_length=5, verbose_name=b"R\xc3\xa9glement de l'accompte"),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_seat',
            field=models.BooleanField(default=False, verbose_name=b'Si\xc3\xa8ge enfant'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payement_type',
            field=models.CharField(default=b'Aucun', max_length=5),
        ),
        migrations.AddField(
            model_name='buissnesspartner',
            name='status',
            field=models.CharField(default=b'inactif', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.BuissnessPartner'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default=b'inactif', max_length=100),
        ),
        migrations.AddField(
            model_name='commercial',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.BuissnessPartner'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='status',
            field=models.CharField(default=b'inactif', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(default=b'inactif', max_length=100),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name=b'Nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='luggage_number',
            field=models.IntegerField(verbose_name=b'Nombre de baggages'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default=b'Ajout dans panier', max_length=100),
        ),
        migrations.AlterField(
            model_name='buissnesspartner',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='revenues',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Revenues'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='luggage_number',
            field=models.IntegerField(help_text=b'Nombre de bagage authoris\xc3\xa9', verbose_name=b'Nombre de baggage maximun'),
        ),
        migrations.AddField(
            model_name='bookingoperator',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Client'),
        ),
        migrations.AddField(
            model_name='bookingoperator',
            name='model_choose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.VehicleModel', verbose_name=b'Mod\xc3\xa8le souhait\xc3\xa9e'),
        ),
        migrations.AddField(
            model_name='bookingoperator',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Operator'),
        ),
        migrations.AddField(
            model_name='bookingoperator',
            name='vehicle_choose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Vehicle', verbose_name=b'Voiture'),
        ),
    ]
