# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0002_auto_20171120_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='buissnesspartner',
            name='status',
            field=models.CharField(default=b'Inactive', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default=b'Inactive', max_length=100),
        ),
        migrations.AddField(
            model_name='commercial',
            name='status',
            field=models.CharField(default=b'Inactive', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(default=b'Inactive', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='luggage_number',
            field=models.IntegerField(verbose_name=b'Nombre de baggages'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default=b'En cours de validation', max_length=100),
        ),
    ]
