# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0002_travel_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_see_its_booking', 'Can drive'),)},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'permissions': (('can_see_its_booking', 'Can drive'),)},
        ),
    ]
