# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0002_auto_20171029_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='clients',
            new_name='bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='departure',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='order_choose',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
