# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0002_auto_20170807_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
