# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0002_auto_20171026_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='remuneration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='revenues',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
