# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0002_auto_20180128_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_stripe',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='number_place',
            field=models.IntegerField(verbose_name=b'Passager(s) par voyage'),
        ),
    ]
