# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0003_auto_20171125_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buissnesspartner',
            name='status',
            field=models.CharField(default=b'inactif', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(default=b'inactif', max_length=100),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='status',
            field=models.CharField(default=b'inactif', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(default=b'inactif', max_length=100),
        ),
    ]
