# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0003_auto_20180211_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='airport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Airport', verbose_name=b'A\xc3\xa9roport de d\xc3\xa9part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Area', verbose_name=b'Zone'),
            preserve_default=False,
        ),
    ]
