# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0003_auto_20171029_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='order_choose',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='bookings',
        ),
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
