# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0004_auto_20171129_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.BuissnessPartner'),
        ),
    ]
