# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0004_auto_20171029_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='order_choose',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
