# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0004_vehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='travel',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Driver'),
        ),
    ]
