# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0005_auto_20171029_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='destination',
        ),
        migrations.AddField(
            model_name='travel',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='Back_Source.Booking'),
        ),
    ]
