# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 17:09
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0005_auto_20170814_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pos',
            field=geoposition.fields.GeopositionField(default=None, max_length=42),
            preserve_default=False,
        ),
    ]
