# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0006_auto_20180303_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoperator',
            name='time_estimated',
            field=models.IntegerField(default=None, verbose_name=b'Temps estim\xc3\xa9 en secondes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_estimated',
            field=models.IntegerField(verbose_name=b'Temps estim\xc3\xa9 en secondes'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Arriv\xc3\xa9e'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'D\xc3\xa9part Pr\xc3\xa9vue'),
        ),
    ]
