# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 18:07
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0006_vehicle_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='long',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pos',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
