# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0006_auto_20171029_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_choose',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
