# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0006_client_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='account',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='accountType',
            field=models.CharField(default=b'CB', max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='revenues',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Revenues'),
        ),
    ]
