# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0007_auto_20171029_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='order_choose',
            new_name='distance',
        ),
    ]
