# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0007_auto_20180303_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='done',
            field=models.BooleanField(default=False, verbose_name=b'R\xc3\xa9alis\xc3\xa9'),
            preserve_default=False,
        ),
    ]
