# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0007_auto_20171201_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payement_type',
            field=models.CharField(default=b'Aucun', max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='account',
            field=models.IntegerField(default=5, verbose_name=b'Accompte'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accountType',
            field=models.CharField(default=b'CB', max_length=5, verbose_name=b"R\xc3\xa9glement de l'accompte"),
        ),
    ]
