# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 16:20
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0008_auto_20171029_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='departure',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
