# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0008_auto_20171201_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('destination_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('date', models.DateField(auto_now=True, verbose_name=b'Date R\xc3\xa9servation')),
                ('passengers', models.IntegerField(verbose_name=b'Nombre de passagers')),
                ('luggage_number', models.IntegerField(verbose_name=b'Nombre de baggages')),
                ('flight', models.CharField(max_length=200, verbose_name=b'Vol')),
                ('arrive_time', models.DateTimeField(blank=True, verbose_name=b"Date d'Arriv\xc3\xa9e")),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name=b'Distance D\xc3\xa9part-Destination')),
                ('status', models.CharField(default=b'En cours de validation', max_length=100)),
                ('payement_type', models.CharField(default=b'Aucun', max_length=5)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Airport', verbose_name=b'A\xc3\xa9roport')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Client')),
                ('model_choose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.VehicleModel', verbose_name=b'Mod\xc3\xa8le souhait\xc3\xa9e')),
                ('vehicle_choose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Vehicle', verbose_name=b'Voiture')),
            ],
            options={
                'verbose_name': 'R\xe9servation Op\xe9rateur',
                'verbose_name_plural': 'R\xe9servations Op\xe9rateur',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('buissnesspartner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Back_Source.BuissnessPartner')),
            ],
            options={
                'verbose_name': 'Op\xe9rateur',
            },
            bases=('Back_Source.buissnesspartner',),
        ),
    ]
