# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0009_auto_20180304_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
