# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0009_auto_20171101_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Zone'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'R\xe9servation'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Chauffeur'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Trajet'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Voiture'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Mod\xe8le de voiture', 'verbose_name_plural': 'Mod\xe8les de voiture'},
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='image_default',
            field=models.URLField(blank=True, null=True, verbose_name=b'Image'),
        ),
        migrations.AlterField(
            model_name='area',
            name='east',
            field=models.FloatField(verbose_name=b"Limite \xc3\xa0 l'est"),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=1000, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='area',
            name='north',
            field=models.FloatField(verbose_name=b'Limite au Nord'),
        ),
        migrations.AlterField(
            model_name='area',
            name='south',
            field=models.FloatField(verbose_name=b'Limite au Sud'),
        ),
        migrations.AlterField(
            model_name='area',
            name='west',
            field=models.FloatField(verbose_name=b"Limit \xc3\xa0 l'ouest"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrive_time',
            field=models.DateTimeField(blank=True, verbose_name=b'Date R\xc3\xa9serv\xc3\xa9'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now=True, verbose_name=b'Date R\xc3\xa9servation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure',
            field=geoposition.fields.GeopositionField(max_length=42, verbose_name=b'Position du d\xc3\xa9part'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=geoposition.fields.GeopositionField(max_length=42, verbose_name=b'Position de la destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Distance D\xc3\xa9part-Destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.CharField(max_length=200, verbose_name=b'Vol'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='luggage_number',
            field=models.IntegerField(verbose_name=b'Volume des baggages'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(verbose_name=b'Nombre de passagers'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_choose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Vehicle', verbose_name=b'Voiture'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(verbose_name=b'Age'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(max_length=10, verbose_name=b'Sexe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name=b'Pr\xc3\xa9nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment',
            field=models.CharField(blank=True, max_length=5, verbose_name=b'Type de Payement'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name=b'T\xc3\xa9l\xc3\xa9phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Utilisateur'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='age',
            field=models.IntegerField(verbose_name=b'Age'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(max_length=10, verbose_name=b'Sexe'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name=b'Pr\xc3\xa9nom'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name=b'T\xc3\xa9l\xc3\xa9phone'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='remuneration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'R\xc3\xa9mun\xc3\xa9ration'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='revenues',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Revenues'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Utilisateur'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='Back_Source.Booking', verbose_name=b'R\xc3\xa9servations'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Vehicle', verbose_name=b'Voiture'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Driver', verbose_name=b'Chauffeur'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name=b'Arriv\xc3\xa9e'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name=b'D\xc3\xa9part'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Area', verbose_name=b'Zone assign\xc3\xa9'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='back',
            field=models.ImageField(upload_to=b'', verbose_name=b'Photo Arri\xc3\xa8re'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=100, null=True, verbose_name=b'Couleur'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Driver', verbose_name=b'Chauffeur'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='empty_luggages',
            field=models.IntegerField(verbose_name=b'Volume disponible pour le coffre'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='empty_places',
            field=models.IntegerField(verbose_name=b'Place disponible'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front',
            field=models.ImageField(upload_to=b'', verbose_name=b'Photo Avant'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance',
            field=models.FileField(upload_to=b'', verbose_name=b"Contrat d'Assurance"),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_card',
            field=models.FileField(upload_to=b'', verbose_name=b'Carte Verte'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Back_Source.VehicleModel', verbose_name=b'Mod\xc3\xa8le'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pos',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, verbose_name=b'Position'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(max_length=9, verbose_name=b'Immatriculation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_card',
            field=models.FileField(upload_to=b'', verbose_name=b'Carte Grise'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='revenues',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Revenues'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='travelling',
            field=models.BooleanField(default=False, verbose_name=b'En voyage'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.CharField(max_length=200, verbose_name=b'Marque'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='category',
            field=models.CharField(max_length=100, verbose_name=b'Cat\xc3\xa9gorie'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='child_seat',
            field=models.BooleanField(verbose_name=b'Si\xc3\xa8ge enfant'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='luggage_number',
            field=models.IntegerField(help_text=b'Taille du coffre en litre', verbose_name=b'Volume du coffre'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model',
            field=models.CharField(max_length=200, verbose_name=b'Mod\xc3\xa8le'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='number_place',
            field=models.IntegerField(verbose_name=b'Places'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year',
            field=models.CharField(max_length=4, verbose_name=b'Ann\xc3\xa9e'),
        ),
    ]
