# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0009_bookingoperator_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoperator',
            name='operator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Operator'),
            preserve_default=False,
        ),
    ]
