# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0010_auto_20171109_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='doors',
            field=models.IntegerField(default=5, verbose_name=b'Portes'),
        ),
    ]
