# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0010_bookingoperator_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='child_seat',
            field=models.BooleanField(default=False, verbose_name=b'Si\xc3\xa8ge enfant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default=b'Ajout dans panier', max_length=100),
        ),
    ]
