# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0011_auto_20180107_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoperator',
            name='city',
            field=models.CharField(default='France', max_length=200, verbose_name=b'Ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buissnesspartner',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Ville'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Ville'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Ville'),
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Ville'),
        ),
    ]
