# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0011_auto_20180304_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.Vehicle', verbose_name=b'Voiture'),
        ),
    ]
