# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0011_vehiclemodel_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
