# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0011_auto_20171025_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='south',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
