# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0012_vehiclemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='model_choose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Back_Source.VehicleModel', verbose_name=b'Mod\xc3\xa8le souhait\xc3\xa9e'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrive_time',
            field=models.DateTimeField(blank=True, verbose_name=b"Date d'Arriv\xc3\xa9e"),
        ),
    ]
