# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0013_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoperator',
            name='price',
            field=models.IntegerField(default=0, verbose_name=b'Prix'),
            preserve_default=False,
        ),
    ]
