# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back_Source', '0014_bookingoperator_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buissnesspartner',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name=b'Pr\xc3\xa9nom'),
        ),
        migrations.AlterField(
            model_name='buissnesspartner',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name=b'Pr\xc3\xa9nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name=b'Pr\xc3\xa9nom'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name=b'Pr\xc3\xa9nom'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pos',
            field=models.CharField(blank=True, max_length=1000, verbose_name=b'Position'),
        ),
    ]
