from booking import BookingSerializer, BookingCommercialSerializer, BookingPartenerSerializer, BookingOperatorSerializer
from person import ClientSerializer, DriverSerializer, CommercialSerizalizer, PartenerSerializer, OperatorSerializer
from travel import TravelSerializer
from vehicle import VehicleSerializer, VehicleModelSerializer
from location import AirportSerializer

